version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_bakery
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: bakery_user
      MONGO_INITDB_ROOT_PASSWORD: bakery_pass
      MONGO_INITDB_DATABASE: bakery_db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
